job_name: test
trigger:
  type: cron
  config:
    schedule: "*/10 * * * * *"
    spchedule: "*/10 * * * * *"


tasks:
  - id: t1
    type: http
    config:
      method: GET
      url: "https://jsonplaceholder.typicode.com/users/1"
      response_type: json
    output: user
    dependencies: [t2]

    on_error:
      action: fail

  - id: t2
    type: http
    config:
      method: GET
      url: "https://jsonplaceholder.typicode.com/${user3.byu}/${user2.id}"
      response_type: json
      headers: "Authorization: user.token"
    output: user1

    on_error:
      action: fail