job_name: test
trigger:
  type: cron
  config:
    schedule: "*/10 * * * * *"


tasks:
  - id: t1
    type: http
    config:
      method: GET
      url: "https://jsonplaceholder.typicode.com/users/1"
      response_type: json
    output: user
    dependencies: [t2]
    on_error:
      action: fallback
      config:
        fallback: t2

  - id: t2
    type: http
    config:
      method: GET
      url: "https://jsonplaceholder.typicode.com/users/1"
      response_type: json
    output: user1
